# Getting started with Pandas

1. Official Pandas tutorial (https://pandas.pydata.org/)
2. Pandas is one of the most used library for data science

In [4]:
import pandas as pd
import numpy as np


#Pandas has two main data structures:

1.Series

2.Dataframe

In [5]:
from pandas import Series, DataFrame

## Introduction to pandas Data Structures

## Series
1. Sequence of values similar to numpy types
2. Associated to data labels


In [ ]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

- Left side represents the index (data labels)

- Right side represents the data

In [ ]:
obj.values

array([ 4,  7, -5,  3])

In [ ]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

We can associate a label to each data point 

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [ ]:
obj2['a']

-5

In [ ]:
obj2[2]

-5

In [ ]:
obj2[:2]

d    4
b    7
dtype: int64

In [ ]:
obj2[-3:]

b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2['a':]

a   -5
c    3
dtype: int64

### Numpy-like operations
1. Filtering with a boolean array
2. Scalar multiplication
3. Applying math functions

They will preserve the index-value link

In [ ]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2>2

d     True
b     True
a    False
c     True
dtype: bool

In [ ]:
selezione = obj2[obj2 > 2]
selezione

d    6
b    7
c    3
dtype: int64

### Math operations

Element wise casting 

Given $ X = \left[ x_1 \cdots x_n \right] $ then:<br> $ X * 2  = \left[ 2 x_1  \cdots 2{x_n} \right]
$
 <br> $
e^X = \left[ e^{x_1} \cdots e^{x_n} \right]
$



In [ ]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

- Another way to think about a Series is as a fixed-length, ordered dict, as it is a mapping of index values to data values.
- You might use a dict.

In [ ]:
display(
  obj2.to_dict(),
  obj2.to_dict().keys(),
  obj2.to_dict().values())

# Recall obj2 = pd.Series([6, 7, -5, 3], index=['d', 'b', 'a', 'c'])

{'a': -5, 'b': 7, 'c': 3, 'd': 6}

dict_keys(['d', 'b', 'a', 'c'])

dict_values([6, 7, -5, 3])

In [ ]:
dizionario = { 'chiave': 5 }
if 'chiave1' in dizionario:
  print("Presente")
else:
  print("Non presente")

Non presente


In [ ]:
'a' in obj2

True

In [ ]:
'f' in obj2

False

### Create a Series from a dictionary

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
float_serie = obj3.astype('float')
float_serie

Ohio      35000.0
Texas     71000.0
Oregon    16000.0
Utah       5000.0
dtype: float64

In [ ]:
obj3.dtype

dtype('int64')

In [ ]:
obj3['Ohio']

35000

- The index in the resulting Series will have the dict's keys in sorted

- Force order of the index

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [1]:
pd.isnull(obj4)

NameError: ignored

In [ ]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
serie = pd.Series([1,2,3,4], index=list('abcd'))
serie

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
serie['a']

1

In [ ]:
serie[0]

1

### Use alignment of indexes for some operations

In [ ]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [ ]:
obj4.name = 'population'
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [ ]:
obj4.index.name = 'state'

In [ ]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [ ]:
obj10 = pd.Series([4,7,-5,3], index = ['Bob', 'Steve', 'Jeff', 'Ryan'])
obj10

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame
1. Represent a rectangular table
2. Ordered collection of columns
3. Each column could have a different type (i.e., numeric, string, boolean, etc.)
4. Dataframe has indexes on columns and rows

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [ ]:
frame

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


The head method selects only the first five rows (good for large datasets)

In [ ]:
frame.shape

(6, 3)

In [ ]:


frame.head(3) # default: 5

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6


In [ ]:
frame.tail(3)

,state,year,pop
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [ ]:
frame.sample(3) # default: 1

,state,year,pop
3,Nevada,2001,2.4
5,Nevada,2003,3.2
0,Ohio,2000,1.5


In [ ]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [ ]:
frame.index.values

array([0, 1, 2, 3, 4, 5])

If you specify a sequence of columns, the DataFrame’s columns will be arranged in that order

In [ ]:
matrix = np.arange(4).reshape(2,-1)
matrix

array([[0, 1],
       [2, 3]])

In [ ]:
table = pd.DataFrame(matrix, columns=['col1', 'col2'], index=['row1', 'row2'])
table

,col1,col2
row1,0,1
row2,2,3


In [ ]:
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003]}

In [ ]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


In [16]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2

,year,state,pop,debt
one,NaN,NaN,NaN,NaN
two,NaN,NaN,NaN,NaN
three,NaN,NaN,NaN,NaN
four,NaN,NaN,NaN,NaN
five,NaN,NaN,NaN,NaN
six,NaN,NaN,NaN,NaN


In [11]:
dato = np.array([[1,2,3],[4,5,6]])
dato

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
frame = pd.DataFrame(dato, columns=['a','s','k'])
frame

,a,s,k
0,1,2,3
1,4,5,6


In [ ]:
frame.columns

Index(['a', 's', 'k'], dtype='object')

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

A column in a DataFrame can be retrieved as a Series either by dict-like notation or by attribute

In [ ]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
type(frame2['year'])

pandas.core.series.Series

In [ ]:
type(frame2)

pandas.core.frame.DataFrame

In [ ]:
display(
  frame2.year, '---',
  frame2['year'])

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

'---'

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Rows can also be retrieved by position or name with the special loc attribute

In [ ]:
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,NaN
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,NaN
five,2002,Nevada,2.9,NaN
six,2003,Nevada,3.2,NaN


In [ ]:
frame2['year'][0] # or frame2.year[0]

2000

In [ ]:
frame2.loc['three'] # NOT work frame2['three'] --> [] takes strings only as columns

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [ ]:
frame

,a,s,k
0,1,2,3
1,4,5,6


### Indexing, Selection, and Filtering

- *loc*: Access a group of rows and columns by label(s) or a boolean array.
- *iloc*: Purely integer-location based rows and columns indexing for selection by position.
- [...]: Access rows by integer or labels, or access columns with labels(no slice for columns in [...]).

columns can be always omitted.

In [6]:
data = pd.DataFrame(np.arange(20).reshape((4, 5)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['zero', 'one', 'two', 'three', 'four'])
data

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


#### columns indexing

In [ ]:
data['one'] # equal to 
# data.loc[:,'one']
# data.iloc[:,0]

Ohio         1
Colorado     6
Utah        11
New York    16
Name: one, dtype: int64

In [ ]:
data[['one']]

,one
Ohio,1
Colorado,6
Utah,11
New York,16


In [ ]:
data["Ohio","Colorado"]

KeyError: ignored

In [ ]:
data[['three', 'two', 'one']] # equals to 
# data.loc[:,['three', 'two', 'one']] 
# data.iloc[:,[2,1,0]]

,three,two,one
Ohio,3,2,1
Colorado,8,7,6
Utah,13,12,11
New York,18,17,16


In [ ]:
data.loc["Ohio":"Colorado", "two"]

Ohio        2
Colorado    7
Name: two, dtype: int64

In [ ]:
display( # sulle colonne
data['three'],
data[['three']],
data[['one', 'two']],
)

Ohio         3
Colorado     8
Utah        13
New York    18
Name: three, dtype: int64

,three
Ohio,3
Colorado,8
Utah,13
New York,18


,one,two
Ohio,1,2
Colorado,6,7
Utah,11,12
New York,16,17


In [ ]:
#SLICE
data.loc[:, 'two':] # or
#data.iloc[:, 2:]
# data['two':] is NOT working

,two,three,four
Ohio,2,3,4
Colorado,7,8,9
Utah,12,13,14
New York,17,18,19


#### row indexing

In [ ]:
data

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [ ]:
data[1:] # equals to 
# data.loc['Colorado':]
# data.iloc[1:]

,zero,one,two,three,four
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [ ]:
data[0:2] #--> [] by integer
# equals to 
# data.loc['Ohio':'Colorado']
# data.iloc[0:2]
# data['Ohio':'Colorado'] # --> [] by label

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9


In [ ]:
data.loc['Colorado']
# data['Colorado'] # does not work >>> None of [Index(['Colorado'], dtype='object')] are in the [columns] <<< --> in [] single labels are only for columns
# data.iloc[1]

zero     5
one      6
two      7
three    8
four     9
Name: Colorado, dtype: int64

In [ ]:
data.loc[['Colorado']] 
# data['Colorado':'Colorado']
# data.iloc[[1]]

,zero,one,two,three,four
Colorado,5,6,7,8,9


In [ ]:
# Row and columns selection
# Examples
data.loc['Ohio':'Colorado', 'three'] # data.loc[[row], [col]] -> label
data.loc['Colorado', ['two', 'three']] # data
data.loc['Ohio':'Colorado', 'three':'four']
data.iloc[[1, 2], 1:2]
data.loc[:'Utah', 'two']
data.iloc[0:2, :] # data.iloc[[row], [col]] -> posizionale
data.iloc[2:3, [3, 0, 1]] # Utah, cols: four, one, two

,three,zero,one
Utah,13,10,11


Why use loc? Differences between [] and .loc[]

1.   using **.loc**, the execution time is more than 3X times faster!

2.   loc is explicit: df.loc[row_indexer, column_index] can select rows and columns.

 df[indexer] can only select rows or columns depending on the type of values in indexer and the type of column values df has (again, are they boolean?).

3.  When a slice is passed to **df.loc** the **end-points are included** in the range. When a slice is passed to **df[...]**, the slice is interpreted as a **half-open** interval:

```
x = pd.DataFrame(np.arange(9).reshape(3,3))
x.loc[1:2].index.values # [1,2]
x[1:2].index.values # [1]
```



#### Filtering

In [ ]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [ ]:
data[data['three'] > 5]
# data.loc[data['three'] > 5]
# data.iloc[data['three'] > 5] # NOT working >>> iLocation based boolean indexing cannot use an indexable as a mask

,zero,one,two,three,four
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


In [ ]:
data >= 12

,zero,one,two,three,four
Ohio,False,False,False,False,False
Colorado,False,False,False,False,False
Utah,False,False,True,True,True
New York,True,True,True,True,True


In [ ]:
data[data >= 12]
# Does NOT work with loc & iloc

,zero,one,two,three,four
Ohio,NaN,NaN,NaN,NaN,NaN
Colorado,NaN,NaN,NaN,NaN,NaN
Utah,NaN,NaN,12.0,13.0,14.0
New York,15.0,16.0,17.0,18.0,19.0


In [ ]:
data.iloc[:, :3][(data.three > 5) & (data['four'] <100)] # combination

,zero,one,two
Colorado,5,6,7
Utah,10,11,12
New York,15,16,17


#### Modify a DataFrame

In [7]:
data_copy_reference = data
data_copy = data.copy()
data_view = data.iloc[2:,1:-1]

In [8]:
data_copy_reference[data_copy_reference >= 12] = 100
data_copy_reference

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,100,100,100
New York,100,100,100,100,100


In [ ]:
data

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,100,100,100
New York,100,100,100,100,100


In [ ]:
data_view

,one,two,three
Utah,11,100,100
New York,100,100,100


In [ ]:
data_copy

,zero,one,two,three,four
Ohio,0,1,2,3,4
Colorado,5,6,7,8,9
Utah,10,11,12,13,14
New York,15,16,17,18,19


Columns can be modified by assignment.

In [15]:
frame2

NameError: ignored

In [17]:
frame2['debt'] = 16.5 
frame2
# 16.5 is **broadcasted** to [16.5, 16.5, ...] == [16.5] * frame2['debt'].shape[0]

,year,state,pop,debt
one,NaN,NaN,NaN,16.5
two,NaN,NaN,NaN,16.5
three,NaN,NaN,NaN,16.5
four,NaN,NaN,NaN,16.5
five,NaN,NaN,NaN,16.5
six,NaN,NaN,NaN,16.5


When you are assigning lists or arrays to a column, the value’s length must match the length of the DataFrame.

In [18]:
frame2['debt'] = [2,15.7,80,98,12,12]
frame2

,year,state,pop,debt
one,NaN,NaN,NaN,2.0
two,NaN,NaN,NaN,15.7
three,NaN,NaN,NaN,80.0
four,NaN,NaN,NaN,98.0
five,NaN,NaN,NaN,12.0
six,NaN,NaN,NaN,12.0


In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
frame2['debt'] = np.arange(6.)
frame2

NameError: ignored

In [ ]:
pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

NameError: ignored

## Essential Functionality

In [ ]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [ ]:
pd.DataFrame({'a':[1,2,3], 'b':[1,2,3]})

,a,b
0,1,1
1,2,2
2,3,3


### Dropping Entries from an Axis | .drop

*drop* method

In [ ]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj.drop(['d', 'a'])

b    1.0
e    4.0
dtype: float64

In [ ]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
np.arange(20).reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'])
data

,0,1,2,3
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [ ]:
data.drop(['Colorado', 'Ohio'])#, inplace=False)

In [ ]:
# data.drop('two', axis=1)
data.drop(['two', 'four'], axis=1)

,one,three
Ohio,0,2
Colorado,4,6
Utah,8,10
New York,12,14


In [ ]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


### Arithmetic and Data Alignment

In [19]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])


In [ ]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [20]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])


df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])



In [ ]:
df1

,b,c,d
Ohio,0.0,1.0,2.0
Texas,3.0,4.0,5.0
Colorado,6.0,7.0,8.0


In [ ]:
df2


,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [ ]:
df1 + df2

,b,c,d,e
Colorado,NaN,NaN,NaN,NaN
Ohio,3.0,NaN,6.0,NaN
Oregon,NaN,NaN,NaN,NaN
Texas,9.0,NaN,12.0,NaN
Utah,NaN,NaN,NaN,NaN


In [ ]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [ ]:
df1

,A
0,1
1,2


In [ ]:
df2

,B
0,3
1,4


In [ ]:
df1 + df2

,A,B
0,NaN,NaN
1,NaN,NaN


#### Arithmetic methods with fill values

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [ ]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [ ]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,6.0,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [ ]:
df2.loc[1, 'b'] = np.nan

In [ ]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,NaN,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [ ]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [ ]:
df1-df2

,a,b,c,d,e
0,0.0,0.0,0.0,0.0,NaN
1,-1.0,NaN,-1.0,-1.0,NaN
2,-2.0,-2.0,-2.0,-2.0,NaN
3,NaN,NaN,NaN,NaN,NaN


In [ ]:
df1.sub(df2, fill_value=0)

,a,b,c,d,e
0,0.0,0.0,0.0,0.0,-4.0
1,-1.0,5.0,-1.0,-1.0,-9.0
2,-2.0,-2.0,-2.0,-2.0,-14.0
3,-15.0,-16.0,-17.0,-18.0,-19.0


In [ ]:
1 / df1

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [ ]:
df1 / 1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [ ]:
df2.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [ ]:
df1.reindex(columns=df2.columns, fill_value=100)

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,100
1,4.0,5.0,6.0,7.0,100
2,8.0,9.0,10.0,11.0,100


#### Operations between DataFrame and Series

In [ ]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
arr + 4

array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [ ]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [ ]:
frame - series

,b,d,e
Utah,0.0,0.0,0.0
Ohio,3.0,3.0,3.0
Texas,6.0,6.0,6.0
Oregon,9.0,9.0,9.0


In [ ]:
frame.sub([0,1,2,4], axis='index')

,b,d,e
Utah,0.0,1.0,2.0
Ohio,2.0,3.0,4.0
Texas,4.0,5.0,6.0
Oregon,5.0,6.0,7.0


In [ ]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [ ]:
frame + series2

,b,d,e,f
Utah,0.0,NaN,3.0,NaN
Ohio,3.0,NaN,6.0,NaN
Texas,6.0,NaN,9.0,NaN
Oregon,9.0,NaN,12.0,NaN


In [ ]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [ ]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [ ]:
frame + series3

,Ohio,Oregon,Texas,Utah,b,d,e
Utah,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ohio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oregon,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [ ]:
frame.add(series3, axis='index')

,b,d,e
Utah,1.0,2.0,3.0
Ohio,7.0,8.0,9.0
Texas,13.0,14.0,15.0
Oregon,19.0,20.0,21.0


In [ ]:
frame - series3

,Ohio,Oregon,Texas,Utah,b,d,e
Utah,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ohio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oregon,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [ ]:
frame.sub(series3, axis='columns')

,Ohio,Oregon,Texas,Utah,b,d,e
Utah,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ohio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oregon,NaN,NaN,NaN,NaN,NaN,NaN,NaN


### Function Application and Mapping

- *apply*: Apply a function along an axis of the DataFrame
- applymap: Apply a function to a Dataframe elementwise. This method applies a function that accepts and returns a scalar to every element of a DataFrame

In [ ]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

,b,d,e
Utah,0.252336,-0.266888,-1.022805
Ohio,-0.719798,0.444373,1.515612
Texas,-0.918921,1.156982,-0.770933
Oregon,-1.228038,-1.856218,-0.676014


In [ ]:
frame['b'].max()

0.2523359511720006

In [ ]:
frame['b'].min()

-1.2280376529578898

In [ ]:
f = lambda x: x.max() - x.min()
f

<function __main__.<lambda>>

In [ ]:
def diff_max_min(x): # x pd.Series
  return x.max() - x.min()

In [ ]:
frame

,b,d,e
Utah,0.252336,-0.266888,-1.022805
Ohio,-0.719798,0.444373,1.515612
Texas,-0.918921,1.156982,-0.770933
Oregon,-1.228038,-1.856218,-0.676014


In [ ]:
frame.apply(lambda x: x.max() - x.min())

b    1.480374
d    3.013200
e    2.538417
dtype: float64

In [ ]:
frame.apply(diff_max_min)

In [ ]:
frame.apply(lambda x: x.max() * 100)

In [ ]:
def get_max(x):
  return x.max()

In [ ]:
frame

In [ ]:
frame.apply(get_max, axis='index')

In [ ]:
frame.apply(get_max, axis='columns')

In [ ]:
frame.apply(lambda x: x.max(), axis='columns')

In [ ]:
def f(x):
  return pd.Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

In [ ]:
'%.3f' % 10.100000

In [ ]:
format = lambda x: '%.2f' % x

def get_power_2(x): # x valore
  return np.power(x, 2)

frame.applymap(format)

In [ ]:
frame.applymap(lambda x: '%.2f' % x)

,b,d,e
Utah,0.25,-0.27,-1.02
Ohio,-0.72,0.44,1.52
Texas,-0.92,1.16,-0.77
Oregon,-1.23,-1.86,-0.68


In [ ]:
frame['e'].map(format)

Utah      -1.0228051180301223
Ohio       1.5156120773426829
Texas     -0.7709327432882934
Oregon    -0.6760136434436329
Name: e, dtype: object

## Summarizing and Computing Descriptive Statistics

### Describe

- describe
- sum or cumsum
- mean
- count
- value_counts

In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [ ]:
df.describe()

,one,two
count,3.000000,2.000000
mean,3.083333,-2.900000
std,3.493685,2.262742
min,0.750000,-4.500000
25%,1.075000,-3.700000
50%,1.400000,-2.900000
75%,4.250000,-2.100000
max,7.100000,-1.300000


In [ ]:
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [ ]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [ ]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [ ]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [ ]:
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [ ]:
df.max()

one    7.1
two   -1.3
dtype: float64

In [ ]:
df.idxmax()

one    b
two    d
dtype: object

In [ ]:
df.max()

one    7.1
two   -1.3
dtype: float64

In [ ]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [ ]:
df.cumsum()

,one,two
a,1.40,NaN
b,8.50,-4.5
c,NaN,NaN
d,9.25,-5.8


In [ ]:
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [ ]:
df.describe()

,one,two
count,3.000000,2.000000
mean,3.083333,-2.900000
std,3.493685,2.262742
min,0.750000,-4.500000
25%,1.075000,-3.700000
50%,1.400000,-2.900000
75%,4.250000,-2.100000
max,7.100000,-1.300000


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   one     3 non-null      float64
 1   two     2 non-null      float64
dtypes: float64(2)
memory usage: 256.0+ bytes


### Unique Values, Value Counts, and Membership

In [ ]:
obj = pd.Series(['c', 'a', 'c', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    c
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [ ]:
uniques = obj.unique()
uniques

array(['c', 'a', 'b'], dtype=object)

In [ ]:
obj.value_counts()

c    4
a    3
b    2
dtype: int64

In [ ]:
pd.value_counts(obj.values, sort=True, ascending=True)

b    2
a    3
c    4
dtype: int64

In [ ]:
obj

In [ ]:
obj.map(lambda x: x in ['c', 'a'])

In [ ]:
mask = obj.isin(['c', 'a'])

In [ ]:
mask

In [ ]:
obj[mask]

In [ ]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

In [ ]:
result = data.apply(pd.value_counts).fillna(0)
result

In [ ]:
pd.value_counts(data["Qu1"])

In [ ]:
data.apply(pd.value_counts, axis=1).fillna(0)